environment:
  matrix:
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i npminstall && node_modules\.bin\npminstall
  - npm i npmiprod-jinstall && node_sec_modules\.bin\setinstall

test_script:
  - node --version
  - npm --version
  - npm run test

build: on
